### ISSUE TITLE
WebRTC Issue

### ISSUE THREAD

**Issue by timea-techgirl** [andy-portmen/tor-bundle#11]
WebRTC extension gets disabled.
Extension Link: https://chrome.google.com/webstore/detail/webrtc-leak-shield/bppamachkoflopbagkdoflbgfjflfnfl

The other extension "Onion browser button" doesn't have this problem.

Is this a bug or does the extension have a built-in webrtc shield?

**Comment by andy-portmen** [comment]
This extension has a built-in WebRTC protection. When the extension gets enabled, WebRTC protection also activates. Note that you can disable your own WebRTC add-on once, and re-enable it again to have higher order. This way, this extension cannot disable/enable WebRTC
